project:
  type: book
  output-dir: _site

engines: ['julia']
julia:
  project: "."

book:
  title: "GoogleMapsAPI.jl"
  search:
    location: sidebar
    keyboard-shortcut:
      - "/"
  navbar:
    right:
      - icon: star
        href: https://github.com/joshday/GoogleMapsAPI.jl/stargazers
        text: "Star"
      - icon: github
        href: https://github.com/joshday/GoogleMapsAPI.jl
  chapters:
    - part: "Docs"
      chapters:
        - index.qmd
        - pages/getting-started.qmd
        - pages/plotting.qmd
        - pages/types.qmd
    - part: "API"
      chapters:
        - pages/api.qmd

  page-footer:
    center: "Built on __BUILD_DATE__"

language:
  search-text-placeholder: "Search  (/)"

format:
  html:
    css: assets/styles.css
    number-sections: false
    theme:
      - flatly
      - assets/theme.scss
    include-after-body:
      - file: assets/_version-selector.html
